// Code generated by "stringer -type=ValueSource"; DO NOT EDIT.

package indigo

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Input-0]
	_ = x[Evaluated-1]
}

const _ValueSource_name = "InputEvaluated"

var _ValueSource_index = [...]uint8{0, 5, 14}

func (i ValueSource) String() string {
	if i < 0 || i >= ValueSource(len(_ValueSource_index)-1) {
		return "ValueSource(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ValueSource_name[_ValueSource_index[i]:_ValueSource_index[i+1]]
}
